export interface ComponentData {
  score: number;
  tier: 'entry-level' | 'mid-range' | 'high-end' | 'enthusiast';
  imageUrl?: string;
}

export interface CPUData extends ComponentData {}
export interface GPUData extends ComponentData {}

export const calculatorData = {
  cpus: {
    "AMD Ryzen 9 9950X3D": { score: 125, tier: 'enthusiast' as const },
    "AMD Ryzen 9 9900X3D": { score: 124, tier: 'enthusiast' as const },
    "AMD Ryzen 7 9800X3D": { score: 122, tier: 'enthusiast' as const },
    "AMD Ryzen 9 9950X": { score: 118, tier: 'enthusiast' as const },
    "Intel Core Ultra 9 285K": { score: 116, tier: 'enthusiast' as const },
    "AMD Ryzen 9 9900X": { score: 115, tier: 'enthusiast' as const },
    "AMD Ryzen 7 9700X": { score: 110, tier: 'enthusiast' as const },
    "Intel Core Ultra 7 265K": { score: 108, tier: 'enthusiast' as const },
    "AMD Ryzen 5 9600X": { score: 102, tier: 'enthusiast' as const },
    "Intel Core i9-14900K": { score: 100, tier: 'enthusiast' as const, imageUrl: "https://i.imgur.com/4o7iY2A.png" },
    "AMD Ryzen 9 7950X3D": { score: 98, tier: 'enthusiast' as const, imageUrl: "https://i.imgur.com/S6FE88v.png" },
    "Intel Core i9-13900K": { score: 98, tier: 'enthusiast' as const },
    "Apple M2 Ultra": { score: 98, tier: 'enthusiast' as const },
    "AMD Ryzen 7 7800X3D": { score: 96, tier: 'high-end' as const, imageUrl: "https://i.imgur.com/S6FE88v.png" },
    "Intel Core i7-14700K": { score: 95, tier: 'enthusiast' as const },
    "Apple M1 Ultra": { score: 95, tier: 'enthusiast' as const },
    "AMD Ryzen 9 7900X": { score: 94, tier: 'high-end' as const },
    "Intel Core i9-12900K": { score: 93, tier: 'high-end' as const },
    "AMD Ryzen 7 7700X": { score: 92, tier: 'high-end' as const },
    "Intel Core i7-12700K": { score: 91, tier: 'high-end' as const },
    "Intel Core i5-14600K": { score: 90, tier: 'high-end' as const },
    "Intel Core i7-13700K": { score: 90, tier: 'high-end' as const },
    "Intel Core i5-13600K": { score: 90, tier: 'high-end' as const },
    "AMD Ryzen 9 5950X": { score: 89, tier: 'high-end' as const },
    "AMD Ryzen 5 7600X": { score: 88, tier: 'high-end' as const },
    "Apple M2 Max": { score: 88, tier: 'high-end' as const },
    "AMD Ryzen 5 7600": { score: 87, tier: 'high-end' as const },
    "AMD Ryzen 7 5800X3D": { score: 85, tier: 'high-end' as const },
    "Intel Core i9-11900K": { score: 85, tier: 'high-end' as const },
    "Apple M3 Pro": { score: 85, tier: 'high-end' as const },
    "AMD Ryzen 7 5800X": { score: 84, tier: 'mid-range' as const },
    "Intel Core i7-12700H": { score: 84, tier: 'mid-range' as const },
    "Intel Core i5-12400": { score: 82, tier: 'mid-range' as const },
    "Intel Core i5-12600K": { score: 80, tier: 'mid-range' as const },
    "Intel Core i7-11700K": { score: 80, tier: 'mid-range' as const },
    "AMD Ryzen 9 3950X": { score: 80, tier: 'mid-range' as const },
    "Apple M2 Pro": { score: 80, tier: 'mid-range' as const },
    "AMD Ryzen 5 5600X": { score: 78, tier: 'mid-range' as const },
    "Intel Core i9-10900K": { score: 78, tier: 'mid-range' as const },
    "Apple M3": { score: 78, tier: 'mid-range' as const },
    "Intel Core i5-11600K": { score: 75, tier: 'mid-range' as const },
    "Apple M2": { score: 75, tier: 'mid-range' as const },
    "AMD Ryzen 9 3900X": { score: 75, tier: 'mid-range' as const },
    "Apple M1 Pro": { score: 72, tier: 'mid-range' as const },
    "AMD Ryzen 7 3700X": { score: 72, tier: 'mid-range' as const },
    "Intel Core i7-10700K": { score: 70, tier: 'mid-range' as const },
    "Intel Core i9-9900K": { score: 70, tier: 'mid-range' as const },
    "Apple M1": { score: 68, tier: 'mid-range' as const },
    "AMD Ryzen 5 3600X": { score: 68, tier: 'mid-range' as const },
    "AMD Ryzen 5 3600": { score: 65, tier: 'mid-range' as const },
    "Intel Core i5-10600K": { score: 65, tier: 'mid-range' as const },
    "AMD Ryzen 7 2700X": { score: 62, tier: 'entry-level' as const },
    "Intel Core i5-9600K": { score: 60, tier: 'entry-level' as const },
    "Intel Core i7-8700K": { score: 60, tier: 'entry-level' as const },
  },
  gpus: {
    "NVIDIA GeForce RTX 5090": { score: 140, tier: 'enthusiast' as const },
    "NVIDIA GeForce RTX 5080": { score: 120, tier: 'enthusiast' as const },
    "NVIDIA GeForce RTX 5070 Ti": { score: 105, tier: 'enthusiast' as const },
    "AMD Radeon RX 9070 XT": { score: 102, tier: 'enthusiast' as const },
    "NVIDIA GeForce RTX 4090": { score: 100, tier: 'enthusiast' as const, imageUrl: "https://i.imgur.com/z2x4UG9.png" },
    "AMD Radeon RX 7900 XTX": { score: 98, tier: 'enthusiast' as const, imageUrl: "https://i.imgur.com/mSSTK2B.png" },
    "NVIDIA GeForce RTX 5070": { score: 95, tier: 'enthusiast' as const },
    "NVIDIA GeForce RTX 4080 Super": { score: 95, tier: 'high-end' as const, imageUrl: "https://i.imgur.com/z2x4UG9.png" },
    "Intel Arc Battlemage 24GB": { score: 94, tier: 'high-end' as const },
    "AMD Radeon RX 7900 XT": { score: 92, tier: 'high-end' as const },
    "AMD Radeon RX 9070": { score: 92, tier: 'high-end' as const },
    "NVIDIA GeForce RTX 4070 Ti Super": { score: 90, tier: 'high-end' as const, imageUrl: "https://i.imgur.com/uCHO0Lq.png" },
    "NVIDIA GeForce RTX 3090 Ti": { score: 90, tier: 'high-end' as const },
    "AMD Radeon RX 6950 XT": { score: 88, tier: 'high-end' as const },
    "NVIDIA GeForce RTX 4070 Super": { score: 88, tier: 'high-end' as const },
    "Apple M3 Max (GPU)": { score: 85, tier: 'high-end' as const },
    "NVIDIA GeForce RTX 3080": { score: 85, tier: 'high-end' as const },
    "AMD Radeon RX 7800 XT": { score: 85, tier: 'high-end' as const },
    "NVIDIA GeForce RTX 5060 Ti": { score: 85, tier: 'high-end' as const },
    "AMD Radeon RX 6800 XT": { score: 82, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 3070 Ti": { score: 82, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 4060 Ti": { score: 80, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 3070": { score: 78, tier: 'mid-range' as const },
    "AMD Radeon RX 7700 XT": { score: 78, tier: 'mid-range' as const },
    "Apple M2 Max (GPU)": { score: 78, tier: 'mid-range' as const },
    "AMD Radeon RX 6700 XT": { score: 75, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 3060 Ti": { score: 75, tier: 'mid-range' as const },
    "Apple M3 Pro (GPU)": { score: 75, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 5060": { score: 75, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 2080 Ti": { score: 70, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 4060": { score: 70, tier: 'mid-range' as const },
    "AMD Radeon RX 6700": { score: 70, tier: 'mid-range' as const },
    "Apple M2 Pro (GPU)": { score: 70, tier: 'mid-range' as const },
    "AMD Radeon RX 7600": { score: 68, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 3060": { score: 68, tier: 'mid-range' as const },
    "Apple M3 (GPU)": { score: 68, tier: 'mid-range' as const },
    "AMD Radeon RX 5700 XT": { score: 65, tier: 'mid-range' as const },
    "Apple M2 (GPU)": { score: 65, tier: 'mid-range' as const },
    "AMD Radeon RX 6600 XT": { score: 65, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 2070 Super": { score: 65, tier: 'mid-range' as const },
    "NVIDIA GeForce RTX 5050": { score: 65, tier: 'mid-range' as const },
    "Intel Arc A770": { score: 60, tier: 'entry-level' as const },
    "NVIDIA GeForce GTX 1080 Ti": { score: 60, tier: 'entry-level' as const },
    "AMD Radeon RX 6600": { score: 60, tier: 'entry-level' as const },
  },
  ramImpact: {
    "8": 0.9,
    "16": 1.0,
    "32": 1.05,
    "64": 1.1
  },
  purposeImpact: {
    gaming: { cpu: 0.9, gpu: 1.1 },
    streaming: { cpu: 1.1, gpu: 1.0 },
    video_editing: { cpu: 1.15, gpu: 0.95 },
    "3d_rendering": { cpu: 1.05, gpu: 1.05 },
    general: { cpu: 1.0, gpu: 1.0 }
  },
  resolutionImpact: {
    "1080p": 1.0,
    "1440p": 0.85,
    "4k": 0.65,
    "ultrawide": 0.9
  }
};

export const placeholderImages = {
  cpu: "https://i.imgur.com/PHYyIxl.png",
  gpu: "https://i.imgur.com/Jprx55s.png"
};